### ISSUE TITLE
Multithreading test failed.

### ISSUE THREAD

**Issue by slavap** [tzaeschke/zoodb#103]
See submitted PR https://github.com/tzaeschke/zoodb/pull/102
May be I've missed something obvious, but looks like multithreading usage of ZooDb is broken.

**Comment by tzaeschke** [comment]
Yes, it is. This is actually a known bug. Test_024_xxx fails occasionally and very rarely Test_025_xxx. Or did you see the problem anywhere else, maybe reproducible or a problem with the code?

**Comment by slavap** [comment]
No, just expected that test is working a little bit longer, see my pull request. I fails immediately, I wanted to catch some bugs, but on the later stages, not in the beginning.

**Comment by tzaeschke** [comment]
Ah, sorry, I didn't see the PR. I'll have a look.

**Comment by tzaeschke** [comment]
First of all, thanks for the test, it is quite useful. Unfortunately, I can't pull it, it appears to be Datanucleus' code, I can't simply add it to my code at the moment.

Second, I'm not sure which problems you saw. The one I saw consistently was about Managers having too few Employees. This is due to missing zooActivateRead() calls. If you put zooActivateRead() into Person.hashcode() and equals(), the Manager will always have 100 Employees. HashSets are not terribly efficient at the moment in ZooDB.

Third, while the tests usually runs through on my machine (8 core i4790), using the test I did finally find some of the flaws in my synchronization approach. So thanks for that and I think this is another one that is worth a bounty.

**Comment by slavap** [comment]
Danucleus has Apache2 license, so I believe it's quite compatible with other licenses, even MIT. So please think once again about including adopted tests from them. See here https://www.whitesourcesoftware.com/whitesource-blog/top-10-apache-license-questions-answered/
I will additionally run this tests on my PC, I've consistently got error about corruption of pages.

**Comment by tzaeschke** [comment]
Okay, it looks there was quite a blunder in the code. The default for multi-threading support was set to false, rather than the promised 'true'. If fixed this, but as workaround for older versions one can use the properties `props.setMultiThreaded(true);` or directly the PMF with `pmf.setMultithreaded(true);`.

Yes, Apache 2.0 should be compatible, and I'm considering migrating to Apache 2.0 anyway. I think the least I'd need to do, in addition to accept the PR, is adding a note somewhere that I added other peoples code to my project. I may actually do that, let me think about it.

**Comment by tzaeschke** [comment]
Btw, there is still a chance of multi-threaded failure. I'll debug this further, but it should only occur with multiple PMs, not when all threads operate on the same PM.

**Comment by slavap** [comment]
No, I've adopted "One pm per many threads" test (see updated pull request), and I'm getting spontaneous NPE errors in case of "all threads operate on the same PM", see MultithreadPMTest.testMultipleTransitionRead().  Also I've adopted generics test, it works fine, no problems.
