### ISSUE TITLE
verboseToLog in DBLogger.java

### ISSUE THREAD

**Issue by dtsw** [tzaeschke/zoodb#106]
in DBLogger.java, i dont see a method to set verboseToLog. How am i supposed to get rid of the System.out.println, if verboseToLog ist always false (or what do i miss) :-)
I use zoodb with an example code for JDO in which they do this (adapted to my Objects). See comment in code.

```
    public static Schedule getScheduleByName(PersistenceManager pm, String scheduleName) {
        Extent scheduleExtent = pm.getExtent(Schedule.class, false);
        Query query = pm.newQuery(scheduleExtent, "name == scheduleName");
        query.declareParameters("String scheduleName");
        Collection result = (Collection) query.execute(scheduleName);
        Iterator iter = result.iterator();
        Schedule schedule = (Schedule) (iter.hasNext() ? iter.next() : null);
        query.close(result);            // obviously, this causes "Debug (1): QueryResult not found." on console, if no Schedule was found in DB
        return schedule;
    }
```

**Comment by tzaeschke** [comment]
I think you are right, you may have to modify the code to disable this message with the current release. I think the problem is that a finished query result closes itself, so explicit closing is not required when the result is iterated through until hasNext() returns 'false'. This is a bug and should be fixed.
At the moment I can offer two workarounds:
a) Do not close the query explicitly.
b) Download the branch 'devTZ_main'. The branch replaces the logging with the slf4j framework and allows fine control of what should be logged and what not.

I plan to do a new release within the next two weeks.

**Comment by dtsw** [comment]
great news and thanks for the quick answer. I will probably do a) for the moment and plan b) for the next release of my tool =)
