### ISSUE TITLE
Delete me

### ISSUE THREAD

**Issue by ThreaT** [tzaeschke/zoodb#64]
Delete me

**Comment by tzaeschke** [comment]
I agree that GPL is too restrictive.
ZooDB is likely to get a more open license soon, the decision will be made towards the end of this year.
The current idea is to get a permissive license such as the Apache License (APL), MIT/BSD or maybe Eclipse Public License (EPL).

The Unlicense is an unlikely candidate since it is not approved by the Open Source Initiative (OSI): http://opensource.org/licenses/alphabetical

Also, there seem to be a number of uncertainties with the Unlicense, also regarding patent issues:
https://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

Some links for future reference:
CopyLeft (and APL): https://www.gnu.org/licenses/license-recommendations.html
They explain for example that APL protects users from “bait and switch”-patent suing schemes.

A more detailed discussion of licenses:
https://opensource.com/law/13/1/which-open-source-software-license-should-i-use

**Comment by tzaeschke** [comment]
Btw, thanks for offering to contribute, unfortunately I may not be able to accept pull requests or other contributions until end of the year. There are limitations from my side in term of availability during the next few months. Also, license changes are easier if there are less people who have contributed.

**Comment by ThreaT** [comment]
I understand. The idea behind unlicense is that the community puts all legal matters aside including copyrights and patents. Historically it's been very popular for open source to not be completely open where companies like Google still have the ability to sue a contributor/user if they don't include copyright notices.
